### ISSUE TITLE
[Updated] Updated PGR data with corrected frang and lagfr

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#11]
# Files 
[List files to be updated](http://vt.superdarn.org/assets/docs/ddwg/issue10/modifiedfiles.txt)

## Mirrors To be Updated
- [X] Usask
- [X] BAS

## Description
It was pointed out by Pasha Ponomarenko that between 18UT on 13 March 2015 and 3UT on 23 July 2015 Prince George data had a range offset of one gate. frang and lagfr were adjusted to fix this offset. Corrected data is now on the usask mirror.

Originally, the corrected files had some issues with them. This has been corrected as of Feb. 29, 2016 15 UTC. So if files were downloaded before that time, please redownload the real corrected files.

Attached is a list of corrected files.

## Tasks
- [ ] Remove files listed in modifiedfiles.txt in the Supplemental Materials
- [ ] Resync or download the corrected files from the USask data mirror
- [ ] Reprocess ALL secondary data products including grid and map files as this change will shift the location of the data.
