### ISSUE TITLE
[Blacklisted] Issue #5: High Velocity ksr data - 201110

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#21]
# Proposed File(s)
King Salmon radar in October 2010.

## Affiliated Mirror
- [X] BAS
- [X] USASK
- [ ] VT (holding institute)

## Reason

It came to our attention lately that a year or so ago, Simon Shepherd identified a period of bad data from the King Salmon radar in October 2010.  The velocity recorded in the files in the attached high_vel_ksr.txt file are way high.  It was confirmed (I'm fairly certain) with Jef Spaleta that something was not set correctly during a site visit to repair the radar which resulted in the high velocity values.

The high velocity values can be noticed in the attached RTI plot as well as the map potential plot.  The map-level data was how Simon originally found this error.  We've removed these files and reprocessed our grid and map files at Virginia Tech.  I propose that these rawacf files should also be blacklisted on the data mirror.

I'll be working up a new webpage for this issue but for now, the action items for each institution for this issue should be: 

## Tasks
- [ ]  Remove the rawacf and subsequent processed files (fitacf) that match the attached text file.
- [ ]  Reprocess grid and map files to clear the high velocity data out of the map potential plots.

**Comment by mts299** [comment]
Morning,

For the issue webpage:

The issue was a frequency offset on LO providing the reference clock.
PTS's front panel dial for Hz was not firmly in the zero position (even
though it appeared to be set to zero on visual inspection), so digital
electronics LO was off by +1 Hz from the expected value. If memory
serves it was the reference LO for the DDS card. Never figured out a way
to reprocess rawacf files for the impacted period.

-jef

**Comment by mts299** [comment]
Hello all,

All of the 253 files sent out were found on and removed from the mirror.
The process started at 19:00 and ended at 19:03 UTC.

The files have been added to the blacklist.

Regards,
Kevin Krieger
