### ISSUE TITLE
[Blacklisted]  20181125.14*hok* file issue

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#27]
# Proposed File(s)
20181125.1401.00.hok.rawacf.bz

## Affiliated Mirror
- [ ] BAS
- [X] USASK
- [ ] VT (holding institute) 

## Reason
Hello Data Distribution WG,

We've worked with Nozomu and have identified a corrupted file that passed some checks and was originally placed on data mirrors/archives. Please note that the file 20181125.1401.00.hok.rawacf.bz2 has a corrupted dmap record and is being blacklisted.

This file has been removed off of the BAS mirror so far.

Cheers,
-Kevin S.

## Tasks 
- [x] Remove RAWACF files from the mirrors 
- [x] Add to blacklisted list 
- [x] Reprocess and upper data products

**Comment by mts299** [comment]
Checked removed off the USASK mirror.

**Comment by mts299** [comment]
2019-02-20
Hello All,

I've also blacklisted this file on the Usask mirrors.
Note: I assigned this Issue #31.

Attached is the new master list of blacklisted files for your reference.

Regards,
Kevin Krieger
