### ISSUE TITLE
[Blacklisted] Issue #34 - Two blacklisted CDN files (rkn/sas)

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#35]
# Proposed File(s)
20190702.2207.12.sas.rawacf.bz2
20190709.1644.29.rkn.rawacf.bz2

## Affiliated Mirror
- [ ] BAS
- [ ] USAK
- [ ] VT (holding institute) 

## Reason
Hi DDWG,

I have two files from the CDN radars that should be removed from your
repos and blacklisted.
Our computer at the rkn site died in early July, so we used the old sas
computer to replace it, but during testing and setup of the machine
there were two files generated that contain no real data as they were
not connected to a radar at the time.
They have been removed and blacklisted at USASK.

The files are
20190702.2207.12.sas.rawacf.bz2
20190709.1644.29.rkn.rawacf.bz2

Regards,
Kevin Krieger

## Tasks 
- [ ] Remove RAWACF files from the mirrors 
- [ ] Add to blacklisted list 
- [ ] Reprocess and upper data products
