### ISSUE TITLE
[Blocked] January 2020 KER files

### ISSUE THREAD

**Issue by kevinkrieger** [SuperDARN/DDWG#37]
# Proposed File(s)

1af28a2701937d2f757f4563cc16ee387907c651 20200110.0201.00.ker.rawacf.bz2
dc060f7bbea48bdaf9aa5d8c145095fc1bc277aa 20200110.0401.00.ker.rawacf.bz2
51264ea6b63a5d97e7014d57faeecedc7cf8cc0c 20200110.0601.00.ker.rawacf.bz2
bd7c752890bdb64f0194130aad52ba34209349f0 20200110.0801.00.ker.rawacf.bz2
b113f0b377bbe6742f32aa24671025302817f256 20200111.0201.00.ker.rawacf.bz2
5a6629b032694c8bbd6b5df39398f96dbc6fb782 20200111.0401.00.ker.rawacf.bz2
e91f0594981d56c8490460c46cc93e14e1e091e0 20200111.0702.11.ker.rawacf.bz2
5ab0dddb302d92347e284e58440d3e9f2e4cda5c 20200111.0801.00.ker.rawacf.bz2 

## Affiliated Mirror
- [ ] BAS
- [x] USAK
- [ ] VT (holding institute) 

## Reason
From Aurélie: 

> I send you this email to inform you that the KER radar is currently down
> and has been doing badly during the first semester 2020 due to an
> incompatibility of a new electronic control system and the rest of the
> radar (TX, phasing matrix...), so that all the 2020 data should be at
> least blacklisted or even better removed. 

### Potential Fix
None

## Tasks 
- [ ] Remove RAWACF files from the mirrors 
- [x] Add to blocklist 
- [ ] Notify DDWG
- [ ] Reprocess higher level data products

**Comment by kevinkrieger** [comment]
Blocked at usask on 20200728

**Comment by tjk584** [comment]
Blocked at NSSC
