### ISSUE TITLE
[Blocked] Incorrectly named dat to RAWACF file previous 2006

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#38]
# Proposed File(s)
pervious 2006 with letters in RAWACF files or ".."

## Affiliated Mirror
- [X] BAS
- [X] USAK
- [X] VT (holding institute) 

## Reason
Back when I created RAWACF files to dat files I was unaware of the notion of letters being in the names as there was a convention with stereo radars using letters with the present-day data. I guess these didn't mean the same as I found out later but some got into the mirror by accident and now we are removing them. 

At some point these will become their own folder based on the DDWG workshop meeting, however, this Issue is not discussing that scop. 

## Tasks 
- [ ] Remove RAWACF files from the mirrors 
- [ ] Add to blocklist 
- [ ] Notify DDWG
- [ ] Reprocess RAWACF from dat files with proper naming convention

**Comment by kevinkrieger** [comment]
Removed from and blocked at usask 20200817 ~18:30 UTC

**Comment by kevinkrieger** [comment]
There are more files found with a space for the channel, but no channel.
Here's an example: '20060626.2020.16.pyk..rawacf.bz2'
I've attached this list of files here. 
[files_no_channel.txt](https://github.com/SuperDARN/DDWG/files/5137360/files_no_channel.txt)

**Comment by kevinkrieger** [comment]
Blocked and removed from usask 20200827

**Comment by kevinkrieger** [comment]
To find these with grep:

```grep "[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\.[0-9][0-9][0-9][0-9]\.[0-9][0-9]\.[a-z][a-z][a-z]\.\." *```

**Comment by tjk584** [comment]
NSSC has no files following that pattern.
