### ISSUE TITLE
[Blocked] SAS 20210216 test files

### ISSUE THREAD

**Issue by kevinkrieger** [SuperDARN/DDWG#43]
# Proposed File(s)
- Please list the file(s) you wish to be blocked

20210216.1844.00.sas.a.rawacf
20210216.1849.00.sas.a.rawacf
20210216.1854.00.sas.a.rawacf
20210216.1856.00.sas.a.rawacf
20210216.1858.00.sas.a.rawacf
20210216.1904.00.sas.a.rawacf
20210216.1906.00.sas.a.rawacf
20210216.1908.00.sas.a.rawacf
20210216.1919.00.sas.a.rawacf
20210216.1923.00.sas.a.rawacf
20210216.1927.00.sas.a.rawacf
20210216.1929.00.sas.a.rawacf
20210216.1930.00.sas.a.rawacf

## Affiliated Mirror
- [x] BAS
- [x] USASK
- [x] VT (holding institute) 

## Reason
- Why should this/these file(s) be blocked? They are testing data for stereo operations 
- How does this/these file(s) affect higher level data products? Removal of these requires removal and reprocess of the 20210216 secondary products
- Please include the following to strengthen your reasoning:
     - code for testing or showing your reasoning
     - plots 
     - output 

### Potential Fix
- Is there a way to fix the files to be placed back into the distribution? No
- Please make sure to give a detailed response if there are ways to fix the file(s). This solution will be passed onto the PI of the radar of the proposed file(s) that may wish to fix them instead of blocking them.

## Tasks 
- [x] Remove RAWACF files from the mirrors 
- [x] Add to blocklist 
- [x] Notify DDWG
- [ ] Reprocess higher level data products

**Comment by kevinkrieger** [comment]
Removed from usask mirror : 20220111

**Comment by tjk584** [comment]
Not on NSSC mirror
