### ISSUE TITLE
[Blocked] BKS 20220716

### ISSUE THREAD

**Issue by kevinkrieger** [SuperDARN/DDWG#44]
# Proposed File(s)
- Please list the file(s) you wish to be blocked

20220716.0202.00.bks.rawacf.bz2
20220716.0402.00.bks.rawacf.bz2
20220716.0602.00.bks.rawacf.bz2

## Affiliated Mirror
- [ x] BAS
- [x ] USAK
- [ ] VT (holding institute) 

## Reason
- Why should this/these file(s) be blocked?  K.Sterne emailed DDWG saying they contained no data
- How does this/these file(s) affect higher level data products?
- Please include the following to strengthen your reasoning:
     - code for testing or showing your reasoning
     - plots 
     - output 

### Potential Fix
- Is there a way to fix the files to be placed back into the distribution? No
- Please make sure to give a detailed response if there are ways to fix the file(s). This solution will be passed onto the PI of the radar of the proposed file(s) that may wish to fix them instead of blocking them.

## Tasks 
- [x] Remove RAWACF files from the mirrors 
- [x] Add to blocklist 
- [ ] Notify DDWG
- [ ] Reprocess higher level data products

**Comment by tjk584** [comment]
All files are still on NSSC mirror
