### ISSUE TITLE
[Blocked] hkw 20211012

### ISSUE THREAD

**Issue by kevinkrieger** [SuperDARN/DDWG#45]
# Proposed File(s)
- Please list the file(s) you wish to be blocked

20211012.0601.00.hkw.rawacf.bz2
20211012.0801.00.hkw.rawacf.bz2
20211012.1001.00.hkw.rawacf.bz2
20211012.1201.00.hkw.rawacf.bz2
20211012.1401.00.hkw.rawacf.bz2
20211012.1601.00.hkw.rawacf.bz2
20211012.1624.17.hkw.rawacf.bz2

## Affiliated Mirror
- [x] BAS
- [x] USAK
- [x] VT (holding institute) 

## Reason
- Why should this/these file(s) be blocked? The PI requested these files be blocked
- How does this/these file(s) affect higher level data products?
- Please include the following to strengthen your reasoning:
     - code for testing or showing your reasoning
     - plots 
     - output 

### Potential Fix
- Is there a way to fix the files to be placed back into the distribution? No
- Please make sure to give a detailed response if there are ways to fix the file(s). This solution will be passed onto the PI of the radar of the proposed file(s) that may wish to fix them instead of blocking them.

## Tasks 
- [ ] Remove RAWACF files from the mirrors 
- [ ] Add to blocklist 
- [ ] Notify DDWG
- [ ] Reprocess higher level data products

**Comment by kevinkrieger** [comment]
Blocked and removed on usask mirror 20221223

**Comment by tjk584** [comment]
All files still on NSSC mirror

**Comment by kevinkrieger** [comment]
VT still has them
