### ISSUE TITLE
[Blocked] PGR rawacfs 20060101 incorrect GPS timestamp

### ISSUE THREAD

**Issue by Doreban** [SuperDARN/DDWG#47]
# Proposed File(s)
- Please list the file(s) you wish to be blocked

There are 21 PGR files from 2006 January 01 that should be removed and blocked:
[pgr_2006_blocklist.txt](https://github.com/SuperDARN/DDWG/files/13562832/pgr_2006_blocklist.txt)

## Affiliated Mirror
- [x] BAS
- [x] NSSC
- [x] USAK
- [x] VT (holding institute) 

## Reason
- Why should this/these file(s) be blocked? 
These files were generated by mistake due to a GPS lock error and given an incorrect timestamp. PGR did not make rawacf files in 2006, only dat, so these files should be removed.
- How does this/these file(s) affect higher level data products?
There is only 1-3 integration periods in each file, all over the course of 2 minutes. Multiple mostly empty files all from the same minute, but the data is not from the correct time period.
- Please include the following to strengthen your reasoning:
     - code for testing or showing your reasoning
     - plots 
     - output 

### Potential Fix
- Is there a way to fix the files to be placed back into the distribution?
No, these files should not be in distribution at these times
- Please make sure to give a detailed response if there are ways to fix the file(s). This solution will be passed onto the PI of the radar of the proposed file(s) that may wish to fix them instead of blocking them.

## Tasks 
- [x] Remove RAWACF files from the mirrors 
- [x] Add to blocklist 
- [x] Notify DDWG
- [ ] Reprocess higher level data products

**Comment by Doreban** [comment]
Removed and blocked on usask 20231204.2108

**Comment by ksterne** [comment]
These have been removed from our main data storage area at Virginia Tech.

**Comment by tdbabas** [comment]
These have been removed from the BAS mirror as well.
