### ISSUE TITLE
[Blocked] INV power supply faliure

### ISSUE THREAD

**Issue by Doreban** [SuperDARN/DDWG#48]
# Proposed File(s)
There are 81 files that should be blocked:
[inv_rx_power_faliure.txt](https://github.com/user-attachments/files/16910662/inv_rx_power_faliure.txt)

c9667e3f40ab71120a90fea039b48c318b8f9627  20240829.2200.00.inv.a.rawacf.bz2
095eb1ba8031605ec84bbf6cd177088fbf2c6122  20240830.0000.00.inv.a.rawacf.bz2
704b55a5d2db80ddf481a85f088695b48af4e4cf  20240830.0200.00.inv.a.rawacf.bz2
f4f358297cf934f7718a16bc598f36c8d47189e0  20240830.0400.00.inv.a.rawacf.bz2
784bace4c2c029843cf20a778fd32fc061d5be39  20240830.0600.00.inv.a.rawacf.bz2
55f03fcd04fd82754973b8b03f68b5567ab74743  20240830.0800.00.inv.a.rawacf.bz2
6de8e1c876d67cb73a138df6696d854022b3410f  20240830.1000.00.inv.a.rawacf.bz2
2ef312c0e5c7c342d076c766d9914b83b076457b  20240830.1200.00.inv.a.rawacf.bz2
6535371d1498b41e0f89b08959e7340f622d38c9  20240830.1400.00.inv.a.rawacf.bz2
535920149c106f4192680846eb392271af6b8ab8  20240830.1600.00.inv.a.rawacf.bz2
f34c1d1dc162612dc6616f3b8d0da4577c288560  20240830.1800.00.inv.a.rawacf.bz2
dc96c393dfc9806e642a87cc62ac9b7aeaadc756  20240830.2000.00.inv.a.rawacf.bz2
caf5f688af3ee7afa5b02e2cbceb09d3875ed0cf  20240830.2200.00.inv.a.rawacf.bz2
7f8dcd249e7eba4f8d41fb1c3aaf80eeced0dba4  20240831.0000.00.inv.a.rawacf.bz2
78f05b5c943d38ebbd6019c3fb6e8c345e871702  20240831.0200.00.inv.a.rawacf.bz2
4a298bae53c470df204819d64012c5084ae90a66  20240831.0400.00.inv.a.rawacf.bz2
670e053f96aff0d010d2f3f65838dbebdb4c7cf7  20240831.0600.00.inv.a.rawacf.bz2
7ffb050baf6512f474cbb4bb17cb01b9bd62a1a2  20240831.0800.00.inv.a.rawacf.bz2
657a526345fed96706b5a13ab096100548aa93e2  20240831.1000.00.inv.a.rawacf.bz2
fc8ab7065fd832c2c1ef75e6fdb3168aef754f4f  20240831.1200.00.inv.a.rawacf.bz2
4b3ea11b8e22cc83196508189411db597b3c5b48  20240831.1400.00.inv.a.rawacf.bz2
0fd9d20d15fc98b84dfeb06d6a5ae9184cf5be64  20240831.1600.00.inv.a.rawacf.bz2
60e58e7ab1663a0fe4348126f8d9f122d9bb7f7b  20240831.1800.00.inv.a.rawacf.bz2
cd029ebeb8e4937f5de4d881fdbe15f3abfaa5c0  20240831.2000.00.inv.a.rawacf.bz2
5f966a51fd7848473f147191354aa67a7ecd0775  20240831.2200.00.inv.a.rawacf.bz2
a4b8866eacd2e8652a7b3907f5840138a35f0f18  20240901.0000.00.inv.a.rawacf.bz2
2551dcde016495d1436e9367c076be602521d65f  20240901.0200.00.inv.a.rawacf.bz2
24bd171c19393daacc718bf9fd27fba790a5c9c3  20240901.0400.00.inv.a.rawacf.bz2
c74138afd1d5e4a498c6a09bf4ed42a0ce882c71  20240901.0600.00.inv.a.rawacf.bz2
e3efd0e12b664f55f876aee34d014aa00f160594  20240901.0800.00.inv.a.rawacf.bz2
c615ac04c145f948461364707881f5eddf8eb972  20240901.1000.00.inv.a.rawacf.bz2
a7667cb6e272f602d4fec3f8e33121b826834f73  20240901.1200.00.inv.a.rawacf.bz2
cc2d104e338d59d34d7dbb442a317a931fd0fd49  20240901.1400.00.inv.a.rawacf.bz2
00f8de54e6dc2a9b29a3fc802933f7ec0ab0854c  20240901.1600.00.inv.a.rawacf.bz2
e490736ca7ff1d26a97e295e4a439e464296a306  20240901.1800.00.inv.a.rawacf.bz2
a004267944ddf801bb548a838c449c437e623339  20240901.2000.00.inv.a.rawacf.bz2
67ceb17f401716af718a5cff3e029df8387f7e85  20240901.2200.00.inv.a.rawacf.bz2
843ae9315f1a79c221124d50552efaaf6be286b9  20240902.0000.00.inv.a.rawacf.bz2
b65f6d543e703b1213584f258efe0f5997cb9513  20240902.0200.00.inv.a.rawacf.bz2
db965fbcf1c7aa6a34224a99850700bd97bf29a9  20240902.0400.00.inv.a.rawacf.bz2
51d7453a22a91242bfae9f538c20645d710ed1d2  20240902.0600.00.inv.a.rawacf.bz2
189417de35dd8ef68d8bbe54560d8a02992dffc0  20240902.0800.00.inv.a.rawacf.bz2
dcc7e55a0f17809a0416dfba136245a263fd897d  20240902.1000.00.inv.a.rawacf.bz2
fc6d118368b2e4658e68f9dd1fd1b53c297751a2  20240902.1200.00.inv.a.rawacf.bz2
fa9e8bc23716799a02e75dd9c300335e0e569349  20240902.1400.00.inv.a.rawacf.bz2
b752fa6168ab01695525d4223e7cfcd83eb9ed61  20240902.1600.00.inv.a.rawacf.bz2
7a0a30db2c1c0cb8405317408706a1bc1685a6cc  20240902.1800.00.inv.a.rawacf.bz2
42d8be62fb205b6186c69f4c7d0bd17b00e10a97  20240902.2000.00.inv.a.rawacf.bz2
f52b48921ec791086bc1f3c5a86b202f2aa1e25e  20240902.2200.00.inv.a.rawacf.bz2
0624c4640efe58205511e26b30e205f92f0759d5  20240903.0000.00.inv.a.rawacf.bz2
39101c1c8181af7047a96ea84dfa13a597234898  20240903.0200.00.inv.a.rawacf.bz2
c92fd50e01d95365911a15b76e459e9e0f2c3e6e  20240903.0400.00.inv.a.rawacf.bz2
25f0fdc8e2c5a178d69a95dbdf294ed2c799f4d2  20240903.0600.00.inv.a.rawacf.bz2
e36209c11c47dee68ea51c4f10df23eceb7a2073  20240903.0800.00.inv.a.rawacf.bz2
f8de1fa538bbe1fd944a214f9f4d6c28605c4232  20240903.1000.00.inv.a.rawacf.bz2
a49cee0c2bb6d884992330ec9ef32fe7510634d8  20240903.1200.00.inv.a.rawacf.bz2
8974c112100c370b3f1c18f3236279c4a0ea186f  20240903.1400.00.inv.a.rawacf.bz2
584cdede1fb0fbe7883a50ef298ab59d469d8648  20240903.1413.30.inv.a.rawacf.bz2
f2e6a81badf5f14183eae8927065b36daf6eeae0  20240903.1413.48.inv.b.rawacf.bz2
c170320f73cb31abf649011d9342039cfd868505  20240903.1413.49.inv.c.rawacf.bz2
68eab70f728bed550a8910f0eb43a94ccd441bef  20240903.1413.51.inv.d.rawacf.bz2
5c612b38a07fd38b3dae1b501f105caaedd3c5a9  20240903.1413.52.inv.e.rawacf.bz2
46088920df71e4c9c4446ecd9b7e23b34b4bf7e9  20240903.1413.54.inv.f.rawacf.bz2
e2c3e2b343e73813d192c29a292416d71648bc40  20240903.1413.55.inv.g.rawacf.bz2
481a61b45bb924594b76aa241bbe13513c48cb8a  20240903.1413.57.inv.h.rawacf.bz2
cc03faf246d7aaf3d697d36fbc22f794bcce052c  20240903.1600.00.inv.a.rawacf.bz2
178a54a67abfc0eb8eb7dc4365163097474d922d  20240903.1600.00.inv.b.rawacf.bz2
2fbb662df95bca7af823c3b5c193d96eba8873bc  20240903.1600.00.inv.c.rawacf.bz2
a4a1872ec0415a7f0588075d3103cf5816176a60  20240903.1600.00.inv.d.rawacf.bz2
fba59d97345e762cb70ccfade920fc93ce9baf8e  20240903.1600.00.inv.e.rawacf.bz2
147776d0d1625704dd58e0a12eb23880096010db  20240903.1600.00.inv.f.rawacf.bz2
b9de0caaf756ca7e0563a024f5aa48ef4a3b12db  20240903.1600.00.inv.g.rawacf.bz2
fc8f0e1ce2b9ec285506547119b10710b6126e4b  20240903.1600.00.inv.h.rawacf.bz2
ada2e44c01232933660d7841a82c203289e0cb85  20240903.1650.30.inv.a.rawacf.bz2
8d894514c06f33010af1d87377341030267307e4  20240903.1650.48.inv.b.rawacf.bz2
23ad172259580942c3fdb5fad199addc3a2eca80  20240903.1650.49.inv.c.rawacf.bz2
1bebe77c957623aa5c26849864e798cb0f11ff81  20240903.1650.51.inv.d.rawacf.bz2
ab0c20b0ea15c751f8ffc1565c73c78cc1981519  20240903.1650.52.inv.e.rawacf.bz2
cb811c2183f6de8196a47835ab7c20d6d98d0758  20240903.1650.54.inv.f.rawacf.bz2
7791709e01fce9b88c7d624c703eed50f231fa0b  20240903.1650.55.inv.g.rawacf.bz2
b2a728fc2964d6756e32777e94e9c5d7618c4ecd  20240903.1650.57.inv.h.rawacf.bz2

## Affiliated Mirror
- [x] BAS
- [x] USAK
- [x] NSSC
- [x] VT (holding institute) 

## Reason
- Why should this/these file(s) be blocked? 
A failure of the 15V power supply at INV failed around 22:30 UTC August . While the power supply was broken, the transmitter and receiver chains were not functional and no valid data was collected during this period.
- How does this/these file(s) affect higher level data products?
The data collected consisted of lower power sporadic noise and may impact higher level data products.
- Please include the following to strengthen your reasoning:
Here is an example summary plot from the time period that should be blocked on INV:
![pydarn_20240901_inv a_bm10](https://github.com/user-attachments/assets/dacc43b9-af0c-4a08-91a9-22d0d3facf8a)

### Potential Fix
- Is there a way to fix the files to be placed back into the distribution?
The files cannot be fixed as both the transmitters and receiver chain were down.

## Tasks 
- [x] Remove RAWACF files from the mirrors 
- [x] Add to blocklist 
- [x] Notify DDWG
- [x] Reprocess higher level data products

**Comment by ksterne** [comment]
Thanks for bringing this to our attention!  I've removed the files from our storage at Virginia Tech (VT) and updated the checklist.
