### ISSUE TITLE
[Blacklisted] Corrupt RAWACF files

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#6]
# Proposed File(s)
- [list of files](http://vt.superdarn.org/assets/docs/ddwg/issue26/files_to_remove.txt)

## Affiliated Mirror
- [x] USASK
- [X] BAS
- [ ] VT 
- [X] other holding institutions

## Description
We've recently checked all rawacf files on the mirror. While dmap parsing these files, they are checked for integrity.
The following files attached have corrupted size fields for data buffers, which would lead to out of bounds memory access, among other errors of similar severity.
We've blacklisted them here and are removing them from the public-facing directories of the mirror. Please do the same with your repositories, as you cannot be certain about the data in these files.

## Tasks 
- [ ] Check your local copy for a valid version
- [ ] Blacklist these files from mirrors
- [ ] Remove them from local storage if necessary

**Comment by kevinkrieger** [comment]
Blocked at 
BAS on November 8 2017
USASK on Nov 7 2017

I have no record of VT (@ksterne ) doing anything with these files

**Comment by tjk584** [comment]
Not on NSSC
